target-version = "py310"
line-length = 120
select = [
    "E",
    "W",
    "F",
    "I",
    "B",
    "C4",
]
ignore = [
    "E501",
    "C901",
    "W191",
]
exclude = [
    ".ide",
    ".git",
    "venv",
    "__pycache__",
    "cache",
    "pg_data",
]
